# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('membership', '0002_auto_20160305_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='membership.PeriodType'),
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='end',
            field=models.DateField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='name',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='start',
            field=models.DateField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='periodtype',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='membership.MembershipPeriod'),
        ),
        migrations.AlterField(
            model_name='periodtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_periods', to='membership.MembershipType'),
        ),
    ]
