# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20160312_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Country', verbose_name='nationality'),
        ),
    ]
