# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20160312_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.NullBooleanField(choices=[(0, 'unknown'), (1, 'male'), (2, 'female')], verbose_name='gender'),
        ),
    ]
