# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_sessioncoach_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='registration',
            new_name='attendee',
        ),
        migrations.RenameField(
            model_name='sessioncoach',
            old_name='coach',
            new_name='attendee',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('session', 'attendee')]),
        ),
        migrations.AlterUniqueTogether(
            name='sessioncoach',
            unique_together=set([('session', 'attendee')]),
        ),
    ]
